<?php

$departments = [
    'vh-xh' => [
        'slug' => 'vh-xh',
        'short_name' => 'VH - XH',
        'name' => 'Phòng Văn hóa - Xã hội',
        'badge' => 'Phòng ban chuyên môn',
        'subtitle' => 'Đơn vị tham mưu và tổ chức triển khai các lĩnh vực văn hóa, giáo dục, y tế và chính sách xã hội tại UBND xã Long Hiệp.',
        'summary' => 'Phụ trách văn hóa, giáo dục, y tế, lao động và an sinh xã hội trên địa bàn xã.',
        'manager' => 'Thạch Thanh Mỹ',
        'focus' => 'Văn hóa, giáo dục, y tế, lao động và an sinh xã hội',
        'phone' => '0343.791.397',
        'email' => 'thachthanhmy.lh',
        'hours' => '07:30 - 11:30, 13:30 - 17:00',
        'staff_count' => 10,
        'status_label' => 'Đã có trang chi tiết',
        'detail_available' => true,
        'detail_href' => 'phong-ban-chi-tiet.php?dept=vh-xh',
        'theme' => ['#7b1223', '#c41e3a', '#ef9540'],
        'summary_points' => [
            'Văn hóa, giáo dục, y tế và an sinh xã hội',
            '10 nhân sự phụ trách thường xuyên',
            'Tiếp dân và phối hợp xử lý 5/7 ngày làm việc',
        ],
        'contact_items' => [
            ['label' => 'Trưởng phòng', 'value' => 'Thạch Thanh Mỹ'],
            ['label' => 'Điện thoại', 'value' => '0343.791.397'],
            ['label' => 'Email', 'value' => 'thachthanhmy.lh'],
            ['label' => 'Giờ làm việc', 'value' => '07:30 - 11:30, 13:30 - 17:00'],
        ],
        'key_functions' => [
            'Quản lý văn hóa, thể thao và du lịch trên địa bàn.',
            'Phối hợp công tác giáo dục, y tế và chăm sóc sức khỏe cộng đồng.',
            'Tham mưu chính sách lao động, thương binh, bảo trợ và giảm nghèo.',
            'Tổ chức truyền thông, xây dựng đời sống văn hóa và bình đẳng giới.',
            'Theo dõi công tác dân số, trẻ em và phòng chống bạo lực gia đình.',
            'Kết nối hoạt động giữa nhà trường, trạm y tế, đoàn thể và người dân.',
        ],
        'tasks' => [
            [
                'title' => 'Phát triển đời sống văn hóa cơ sở',
                'description' => 'Tổ chức các chương trình văn nghệ, thể thao, bảo tồn bản sắc văn hóa địa phương và nâng cao chất lượng phong trào toàn dân đoàn kết xây dựng đời sống văn hóa.',
            ],
            [
                'title' => 'Điều phối giáo dục và học tập cộng đồng',
                'description' => 'Theo dõi tình hình trường học, công tác phổ cập, hỗ trợ học sinh có hoàn cảnh khó khăn và kết nối các hoạt động khuyến học tại xã.',
            ],
            [
                'title' => 'Quản lý y tế cơ sở và phòng bệnh',
                'description' => 'Phối hợp với trạm y tế trong các đợt tiêm chủng, khám sức khỏe định kỳ, tuyên truyền vệ sinh môi trường và phòng chống dịch bệnh.',
            ],
            [
                'title' => 'Triển khai chính sách an sinh',
                'description' => 'Thực hiện chính sách người có công, bảo trợ xã hội, hộ nghèo - hộ cận nghèo, chăm lo người cao tuổi, trẻ em và các đối tượng yếu thế.',
            ],
            [
                'title' => 'Công tác dân số và gia đình',
                'description' => 'Tuyên truyền kế hoạch hóa gia đình, nâng cao nhận thức về chăm sóc trẻ em, bình đẳng giới và phòng chống bạo lực gia đình.',
            ],
            [
                'title' => 'Tổng hợp báo cáo và tham mưu UBND xã',
                'description' => 'Tổng hợp dữ liệu chuyên môn, tham mưu các kế hoạch năm, đề xuất giải pháp nâng cao hiệu quả quản lý và phục vụ người dân.',
            ],
        ],
        'activities' => [
            [
                'title' => 'Lễ hội và sự kiện cộng đồng',
                'description' => 'Phối hợp tổ chức các lễ hội truyền thống, ngày hội văn hóa - thể thao và các chương trình kết nối cộng đồng tại xã.',
            ],
            [
                'title' => 'Hỗ trợ giáo dục',
                'description' => 'Vận động học bổng, hỗ trợ sách vở, đồ dùng học tập cho học sinh khó khăn và duy trì các mô hình học tập suốt đời.',
            ],
            [
                'title' => 'Chương trình y tế cộng đồng',
                'description' => 'Truyền thông phòng bệnh, tiêm chủng, chăm sóc sức khỏe ban đầu và nâng cao ý thức phòng ngừa trong nhân dân.',
            ],
            [
                'title' => 'An sinh và tri ân',
                'description' => 'Tổ chức thăm hỏi gia đình chính sách, người có công, người cao tuổi và các đợt vận động hỗ trợ đối tượng khó khăn.',
            ],
        ],
        'staff_members' => [
            ['name' => 'Thạch Thanh Mỹ', 'role' => 'Trưởng phòng Văn hóa - Xã hội', 'phone' => '0343.791.397'],
            ['name' => 'Trần Quốc Hồng', 'role' => 'Phó trưởng phòng Văn hóa - Xã hội', 'phone' => '0853.667.015'],
            ['name' => 'Thạch Ngọc Suyên', 'role' => 'Chuyên viên Văn hóa - Xã hội', 'phone' => '0388.066.800'],
            ['name' => 'Thạch Som', 'role' => 'Chuyên viên Văn hóa - Xã hội', 'phone' => '0976.991.969'],
            ['name' => 'Thạch Quanh Tha', 'role' => 'Chuyên viên Văn hóa - Xã hội', 'phone' => '0375.722.611'],
            ['name' => 'Thạch Ri Tâm', 'role' => 'Phó trưởng phòng Văn hóa - Xã hội', 'phone' => '0976.786.502'],
            ['name' => 'Kim Thu Na', 'role' => 'Chuyên viên Văn hóa - Xã hội', 'phone' => '0949.405.838'],
            ['name' => 'Thạch Thị Sa Rune', 'role' => 'Chuyên viên Văn hóa - Xã hội', 'phone' => '0349.591.818'],
            ['name' => 'Kim Ngọc Chhots', 'role' => 'Chuyên viên Văn hóa - Xã hội', 'phone' => '0338.904.033'],
        ],
        'highlight_stats' => [
            ['value' => '10', 'label' => 'Nhân sự'],
            ['value' => '06', 'label' => 'Nhóm chức năng'],
            ['value' => '04', 'label' => 'Mảng hoạt động trọng tâm'],
            ['value' => '5/7', 'label' => 'Ngày trực tiếp phục vụ người dân'],
        ],
    ],
    'kt' => [
        'slug' => 'kt',
        'short_name' => 'KT',
        'name' => 'Phòng Kinh tế',
        'badge' => 'Đầu mối phát triển kinh tế',
        'subtitle' => 'Theo dõi tình hình sản xuất, thương mại, hạ tầng và các chương trình phát triển kinh tế địa phương.',
        'summary' => 'Phụ trách kinh tế hộ, sản xuất, thương mại và phối hợp hạ tầng phục vụ dân sinh.',
        'manager' => 'Kim Bảy Ly',
        'focus' => 'Nông nghiệp, thương mại, hạ tầng và sinh kế địa phương',
        'phone' => '0944.942.121',
        'email' => 'kimbayly.lh',
        'hours' => '07:30 - 11:30, 13:30 - 17:00',
        'staff_count' => 11,
        'status_label' => 'Đã có trang chi tiết',
        'detail_available' => true,
        'detail_href' => 'phong-kinh-te.php',
        'theme' => ['#0d4f5c', '#16829a', '#6cc7d8'],
        'summary_points' => [
            'Phụ trách kế hoạch sản xuất và phát triển sinh kế',
            'Theo dõi các đầu việc kinh tế - hạ tầng tại xã',
            '11 nhân sự phụ trách thường xuyên',
        ],
        'contact_items' => [
            ['label' => 'Trưởng phòng', 'value' => 'Kim Bảy Ly'],
            ['label' => 'Điện thoại', 'value' => '0944.942.121'],
            ['label' => 'Email', 'value' => 'kimbayly.lh'],
            ['label' => 'Giờ làm việc', 'value' => '07:30 - 11:30, 13:30 - 17:00'],
        ],
        'key_functions' => [
            'Quản lý và theo dõi tình hình sản xuất nông nghiệp trên địa bàn.',
            'Phối hợp triển khai các chương trình phát triển kinh tế địa phương.',
            'Tham mưu chính sách hỗ trợ sản xuất và phát triển sinh kế.',
            'Theo dõi công tác thương mại, dịch vụ và phát triển hạ tầng.',
            'Quản lý đất đai, quy hoạch và các dự án đầu tư.',
            'Kết nối hoạt động giữa hộ sản xuất, doanh nghiệp và chính quyền.',
        ],
        'tasks' => [
            [
                'title' => 'Theo dõi tình hình sản xuất nông nghiệp',
                'description' => 'Giám sát tiến độ sản xuất, hỗ trợ nông dân trong việc áp dụng kỹ thuật mới, quản lý dịch bệnh và nâng cao năng suất cây trồng, vật nuôi.',
            ],
            [
                'title' => 'Triển khai các chương trình phát triển kinh tế',
                'description' => 'Phối hợp thực hiện các chương trình hỗ trợ sản xuất, khuyến nông, khuyến ngư và các dự án phát triển kinh tế - xã hội tại địa phương.',
            ],
            [
                'title' => 'Quản lý đất đai và quy hoạch',
                'description' => 'Theo dõi việc sử dụng đất, cấp giấy chứng nhận quyền sử dụng đất, giải quyết tranh chấp đất đai và triển khai các dự án quy hoạch.',
            ],
            [
                'title' => 'Hỗ trợ phát triển thương mại và dịch vụ',
                'description' => 'Tạo điều kiện cho các hộ kinh doanh, doanh nghiệp hoạt động, kết nối tiêu thụ sản phẩm và phát triển các dịch vụ phục vụ dân sinh.',
            ],
            [
                'title' => 'Quản lý hạ tầng và công trình công cộng',
                'description' => 'Theo dõi tình trạng đường giao thông, thủy lợi, điện nước và các công trình phục vụ sản xuất, đời sống nhân dân.',
            ],
            [
                'title' => 'Tổng hợp báo cáo và tham mưu UBND xã',
                'description' => 'Tổng hợp dữ liệu kinh tế, tham mưu các kế hoạch phát triển, đề xuất giải pháp nâng cao hiệu quả sản xuất và đời sống người dân.',
            ],
        ],
        'activities' => [
            [
                'title' => 'Hỗ trợ sản xuất và khuyến nông',
                'description' => 'Tổ chức các lớp tập huấn kỹ thuật, hỗ trợ giống cây trồng, vật nuôi và liên kết tiêu thụ sản phẩm nông nghiệp.',
            ],
            [
                'title' => 'Phát triển hạ tầng kinh tế',
                'description' => 'Phối hợp triển khai các dự án giao thông, thủy lợi, điện nước phục vụ sản xuất và đời sống.',
            ],
            [
                'title' => 'Kết nối doanh nghiệp và hộ sản xuất',
                'description' => 'Tạo cầu nối giữa doanh nghiệp với nông dân, hỗ trợ tiêu thụ sản phẩm và phát triển chuỗi giá trị.',
            ],
            [
                'title' => 'Quản lý đất đai và giải quyết tranh chấp',
                'description' => 'Hỗ trợ cấp giấy chứng nhận quyền sử dụng đất, giải quyết tranh chấp và quản lý quy hoạch sử dụng đất.',
            ],
        ],
        'staff_members' => [
            ['name' => 'Kim Bảy Ly', 'role' => 'Trưởng phòng Kinh tế', 'phone' => '0944.942.121'],
            ['name' => 'Sơn Ngọc Danh Thái', 'role' => 'Phó trưởng phòng Kinh tế', 'phone' => '0978.630.124'],
            ['name' => 'Kim Thanh Phong', 'role' => 'Chuyên viên Kinh tế', 'phone' => '0384.321.224'],
            ['name' => 'Kim Ngọc Chhộts', 'role' => 'Chuyên viên Kinh tế', 'phone' => '0327.771.40'],
            ['name' => 'Thạch Văn Thi', 'role' => 'Chuyên viên Kinh tế', 'phone' => '0383.976.702'],
            ['name' => 'Dương Quang Vinh', 'role' => 'Chuyên viên Kinh tế', 'phone' => '0985.455.099'],
            ['name' => 'Lê Văn Chắc', 'role' => 'Chuyên viên Kinh tế', 'phone' => '0379.326.461'],
            ['name' => 'Lâm Phước Hoàng', 'role' => 'Chuyên viên Kinh tế', 'phone' => '0985.778.04'],
            ['name' => 'Kim Ngọc Cường', 'role' => 'Chuyên viên Kinh tế', 'phone' => '0375.797.679'],
            ['name' => 'Lê Tấn Phương', 'role' => 'Chuyên viên Kinh tế', 'phone' => '0988.224.059'],
            ['name' => 'Trần Hồng Thủy', 'role' => 'Chuyên viên Kinh tế', 'phone' => 'Đang cập nhật'],
        ],
        'highlight_stats' => [
            ['value' => '11', 'label' => 'Nhân sự'],
            ['value' => '06', 'label' => 'Nhóm chức năng'],
            ['value' => '04', 'label' => 'Mảng hoạt động trọng tâm'],
            ['value' => '5/7', 'label' => 'Ngày trực tiếp phục vụ người dân'],
        ],
    ],
    'van-phong' => [
        'slug' => 'van-phong',
        'short_name' => 'HĐNN',
        'name' => 'Hội đồng Nhân dân Xã',
        'badge' => 'Cơ quan quyền lực nhân dân',
        'subtitle' => 'Hội đồng Nhân dân xã là cơ quan quyền lực nhân dân cấp xã, đại diện cho ý chí, nguyện vọng của nhân dân địa phương.',
        'summary' => 'Phụ trách công tác lập pháp, giám sát và đại diện quyền lực nhân dân tại xã Long Hiệp.',
        'manager' => 'Đang cập nhật',
        'focus' => 'Lập pháp, giám sát và đại diện quyền lực nhân dân',
        'phone' => 'Đang cập nhật',
        'email' => 'hdnn.lh',
        'hours' => '07:30 - 11:30, 13:30 - 17:00',
        'staff_count' => 7,
        'status_label' => 'Đã có trang chi tiết',
        'detail_available' => true,
        'detail_href' => 'phong-hdnn.php',
        'theme' => ['#694518', '#a56f24', '#dfb45d'],
        'summary_points' => [
            'Lập pháp và ban hành các quy định địa phương',
            'Giám sát hoạt động của UBND xã và các cơ quan khác',
            '7 nhân sự đại diện quyền lực nhân dân',
        ],
        'contact_items' => [
            ['label' => 'Người phụ trách', 'value' => 'Đang cập nhật'],
            ['label' => 'Điện thoại', 'value' => 'Đang cập nhật'],
            ['label' => 'Email', 'value' => 'hdnn.lh'],
            ['label' => 'Giờ làm việc', 'value' => '07:30 - 11:30, 13:30 - 17:00'],
        ],
        'key_functions' => [
            'Lập pháp và ban hành các quy định, nghị quyết của địa phương.',
            'Giám sát hoạt động của UBND xã, các cơ quan chuyên môn và tổ chức khác.',
            'Phê chuẩn kế hoạch phát triển kinh tế - xã hội của xã.',
            'Quyết định các vấn đề quan trọng liên quan đến lợi ích chung của nhân dân.',
            'Bầu cử và miễn nhiệm các chức vụ lãnh đạo cấp xã.',
            'Tiếp nhận kiến nghị, phản ánh của nhân dân và giải quyết khiếu nại.',
        ],
        'tasks' => [
            [
                'title' => 'Lập pháp địa phương',
                'description' => 'Ban hành các quy định, nghị quyết phù hợp với tình hình thực tế của xã, đáp ứng nhu cầu phát triển kinh tế - xã hội.',
            ],
            [
                'title' => 'Giám sát hoạt động UBND xã',
                'description' => 'Giám sát việc thực hiện các quyết định của HĐNN, công tác quản lý hành chính và cung cấp dịch vụ công của UBND xã.',
            ],
            [
                'title' => 'Phê chuẩn kế hoạch phát triển',
                'description' => 'Phê chuẩn kế hoạch phát triển kinh tế - xã hội, kế hoạch tài chính - ngân sách và các chương trình phát triển của xã.',
            ],
            [
                'title' => 'Quyết định các vấn đề quan trọng',
                'description' => 'Quyết định về các vấn đề liên quan đến lợi ích chung, phân bổ tài chính, sử dụng đất công cộng và các quyết định quan trọng khác.',
            ],
            [
                'title' => 'Bầu cử và miễn nhiệm lãnh đạo',
                'description' => 'Tổ chức bầu cử, bổ nhiệm, miễn nhiệm các chức vụ lãnh đạo cấp xã theo quy định của pháp luật.',
            ],
            [
                'title' => 'Tiếp nhận kiến nghị và giải quyết khiếu nại',
                'description' => 'Tiếp nhận, xem xét kiến nghị của nhân dân, giải quyết khiếu nại, tố cáo và bảo vệ quyền lợi hợp pháp của người dân.',
            ],
        ],
        'activities' => [
            [
                'title' => 'Kỳ họp HĐNN định kỳ',
                'description' => 'Tổ chức các kỳ họp định kỳ để thảo luận, quyết định các vấn đề quan trọng liên quan đến phát triển xã.',
            ],
            [
                'title' => 'Giám sát chuyên đề',
                'description' => 'Tiến hành giám sát chuyên đề đối với các lĩnh vực quan trọng như giáo dục, y tế, an ninh trật tự.',
            ],
            [
                'title' => 'Tiếp xúc cử tri',
                'description' => 'Tổ chức các buổi tiếp xúc cử tri để lắng nghe ý kiến, kiến nghị của nhân dân và báo cáo kết quả công tác.',
            ],
            [
                'title' => 'Xây dựng pháp luật địa phương',
                'description' => 'Xây dựng, hoàn thiện các quy định, nghị quyết phù hợp với tình hình thực tế và nhu cầu phát triển của xã.',
            ],
        ],
        'staff_members' => [
            ['name' => 'Chủ tịch HĐNN', 'role' => 'Chủ tịch Hội đồng Nhân dân', 'phone' => 'Đang cập nhật'],
            ['name' => 'Phó Chủ tịch HĐNN', 'role' => 'Phó Chủ tịch Hội đồng Nhân dân', 'phone' => 'Đang cập nhật'],
            ['name' => 'Thư ký HĐNN', 'role' => 'Thư ký Hội đồng Nhân dân', 'phone' => 'Đang cập nhật'],
            ['name' => 'Ủy viên HĐNN 1', 'role' => 'Ủy viên Hội đồng Nhân dân', 'phone' => 'Đang cập nhật'],
            ['name' => 'Ủy viên HĐNN 2', 'role' => 'Ủy viên Hội đồng Nhân dân', 'phone' => 'Đang cập nhật'],
            ['name' => 'Ủy viên HĐNN 3', 'role' => 'Ủy viên Hội đồng Nhân dân', 'phone' => 'Đang cập nhật'],
            ['name' => 'Ủy viên HĐNN 4', 'role' => 'Ủy viên Hội đồng Nhân dân', 'phone' => 'Đang cập nhật'],
        ],
        'highlight_stats' => [
            ['value' => '07', 'label' => 'Nhân sự'],
            ['value' => '06', 'label' => 'Nhóm chức năng'],
            ['value' => '04', 'label' => 'Mảng hoạt động trọng tâm'],
            ['value' => '5/7', 'label' => 'Ngày trực tiếp phục vụ người dân'],
        ],
    ],
    'hanh-chinh-cong' => [
        'slug' => 'hanh-chinh-cong',
        'short_name' => 'Hành chính công',
        'name' => 'Bộ phận Hành chính công',
        'badge' => 'Tiếp nhận và trả kết quả',
        'subtitle' => 'Hướng dẫn người dân nộp hồ sơ, theo dõi tiến độ giải quyết thủ tục và trả kết quả theo cơ chế một cửa.',
        'summary' => 'Tiếp nhận hồ sơ, hướng dẫn thủ tục và trả kết quả hành chính cho người dân.',
        'manager' => 'Đang cập nhật',
        'focus' => 'Tiếp nhận hồ sơ, một cửa và hỗ trợ thủ tục',
        'phone' => 'Đang cập nhật',
        'email' => 'hanhchinhcong.lh',
        'hours' => '07:30 - 11:30, 13:30 - 17:00',
        'staff_count' => 6,
        'status_label' => 'Đã có trang chi tiết',
        'detail_available' => true,
        'detail_href' => 'phong-hanh-chinh-cong.php',
        'theme' => ['#22543d', '#2f855a', '#7ccf9a'],
        'summary_points' => [
            'Tiếp nhận và luân chuyển hồ sơ một cửa',
            'Hướng dẫn thủ tục cho người dân và doanh nghiệp',
            '6 nhân sự phụ trách thường xuyên',
        ],
        'contact_items' => [
            ['label' => 'Người phụ trách', 'value' => 'Đang cập nhật'],
            ['label' => 'Điện thoại', 'value' => 'Đang cập nhật'],
            ['label' => 'Email', 'value' => 'hanhchinhcong.lh'],
            ['label' => 'Giờ làm việc', 'value' => '07:30 - 11:30, 13:30 - 17:00'],
        ],
        'key_functions' => [
            'Tiếp nhận hồ sơ hành chính theo cơ chế một cửa, một cửa liên thông.',
            'Hướng dẫn người dân, doanh nghiệp về thủ tục hành chính.',
            'Theo dõi tiến độ giải quyết hồ sơ và đôn đốc các bộ phận liên quan.',
            'Trả kết quả giải quyết thủ tục hành chính cho người dân.',
            'Giải đáp thắc mắc, hỗ trợ kỹ thuật về thủ tục hành chính.',
            'Tổng hợp báo cáo và cải tiến quy trình phục vụ người dân.',
        ],
        'tasks' => [
            [
                'title' => 'Tiếp nhận và kiểm tra hồ sơ',
                'description' => 'Tiếp nhận hồ sơ từ người dân, kiểm tra tính đầy đủ, hợp lệ của hồ sơ và hướng dẫn bổ sung nếu thiếu.',
            ],
            [
                'title' => 'Luân chuyển hồ sơ đến bộ phận chuyên môn',
                'description' => 'Chuyển hồ sơ đến các phòng ban chuyên môn để giải quyết theo đúng thẩm quyền và thời hạn quy định.',
            ],
            [
                'title' => 'Theo dõi tiến độ giải quyết',
                'description' => 'Giám sát tiến độ xử lý hồ sơ, nhắc nhở và đôn đốc các bộ phận để đảm bảo giải quyết đúng hạn.',
            ],
            [
                'title' => 'Trả kết quả cho người dân',
                'description' => 'Thông báo và trao kết quả giải quyết thủ tục hành chính cho người dân theo đúng hẹn.',
            ],
            [
                'title' => 'Hướng dẫn và giải đáp thắc mắc',
                'description' => 'Cung cấp thông tin, hướng dẫn thủ tục và giải đáp các thắc mắc của người dân về thủ tục hành chính.',
            ],
            [
                'title' => 'Tổng hợp báo cáo và cải tiến',
                'description' => 'Tổng hợp số liệu, báo cáo định kỳ và đề xuất cải tiến quy trình để nâng cao chất lượng phục vụ.',
            ],
        ],
        'activities' => [
            [
                'title' => 'Tiếp nhận hồ sơ một cửa',
                'description' => 'Tiếp nhận và xử lý các loại hồ sơ hành chính theo cơ chế một cửa, một cửa liên thông.',
            ],
            [
                'title' => 'Hướng dẫn thủ tục trực tiếp',
                'description' => 'Tư vấn, hướng dẫn người dân về các thủ tục hành chính, giấy tờ cần thiết và quy trình thực hiện.',
            ],
            [
                'title' => 'Theo dõi và đôn đốc giải quyết',
                'description' => 'Giám sát tiến độ xử lý hồ sơ và phối hợp với các phòng ban để đảm bảo giải quyết đúng hạn.',
            ],
            [
                'title' => 'Cải tiến quy trình phục vụ',
                'description' => 'Đề xuất các giải pháp cải tiến quy trình, rút ngắn thời gian và nâng cao chất lượng phục vụ người dân.',
            ],
        ],
        'staff_members' => [
            ['name' => 'Nhân viên 1', 'role' => 'Chuyên viên Hành chính công', 'phone' => 'Đang cập nhật'],
            ['name' => 'Nhân viên 2', 'role' => 'Chuyên viên Hành chính công', 'phone' => 'Đang cập nhật'],
            ['name' => 'Nhân viên 3', 'role' => 'Chuyên viên Hành chính công', 'phone' => 'Đang cập nhật'],
            ['name' => 'Nhân viên 4', 'role' => 'Chuyên viên Hành chính công', 'phone' => 'Đang cập nhật'],
            ['name' => 'Nhân viên 5', 'role' => 'Chuyên viên Hành chính công', 'phone' => 'Đang cập nhật'],
            ['name' => 'Nhân viên 6', 'role' => 'Chuyên viên Hành chính công', 'phone' => 'Đang cập nhật'],
        ],
        'highlight_stats' => [
            ['value' => '06', 'label' => 'Nhân sự'],
            ['value' => '06', 'label' => 'Nhóm chức năng'],
            ['value' => '04', 'label' => 'Mảng hoạt động trọng tâm'],
            ['value' => '5/7', 'label' => 'Ngày trực tiếp phục vụ người dân'],
        ],
    ],
    'ubnd' => [
        'slug' => 'ubnd',
        'short_name' => 'UBND',
        'name' => 'Ủy ban Nhân dân Xã',
        'badge' => 'Cơ quan hành chính nhân dân',
        'subtitle' => 'Ủy ban Nhân dân xã là cơ quan hành chính nhân dân cấp xã, thực hiện chức năng quản lý hành chính, tổ chức thực hiện các quyết định của HĐNN.',
        'summary' => 'Phụ trách quản lý hành chính, điều hành công tác và tổ chức thực hiện các chính sách, pháp luật tại xã Long Hiệp.',
        'manager' => 'Chủ tịch UBND',
        'focus' => 'Quản lý hành chính, điều hành và tổ chức thực hiện chính sách',
        'phone' => 'Đang cập nhật',
        'email' => 'ubnd.lh',
        'hours' => '07:30 - 11:30, 13:30 - 17:00',
        'staff_count' => 8,
        'status_label' => 'Đã có trang chi tiết',
        'detail_available' => true,
        'detail_href' => 'phong-ubnd.php',
        'theme' => ['#1e3a8a', '#3b82f6', '#60a5fa'],
        'summary_points' => [
            'Quản lý hành chính và điều hành công tác xã',
            'Tổ chức thực hiện các quyết định của HĐNN',
            '8 nhân sự lãnh đạo và quản lý',
        ],
        'contact_items' => [
            ['label' => 'Chủ tịch UBND', 'value' => 'Đang cập nhật'],
            ['label' => 'Điện thoại', 'value' => 'Đang cập nhật'],
            ['label' => 'Email', 'value' => 'ubnd.lh'],
            ['label' => 'Giờ làm việc', 'value' => '07:30 - 11:30, 13:30 - 17:00'],
        ],
        'key_functions' => [
            'Quản lý hành chính và tổ chức thực hiện các quyết định của HĐNN.',
            'Tham mưu, đề xuất các chính sách phát triển kinh tế - xã hội.',
            'Quản lý tài chính, ngân sách và tài sản công của xã.',
            'Tổ chức thực hiện công tác an ninh, trật tự và phòng chống tội phạm.',
            'Phối hợp với các cơ quan, tổ chức trong thực hiện các chương trình phát triển.',
            'Tiếp nhận, xử lý kiến nghị, khiếu nại của nhân dân.',
        ],
        'tasks' => [
            [
                'title' => 'Quản lý hành chính xã',
                'description' => 'Tổ chức quản lý hành chính, điều hành công tác và tổ chức thực hiện các quyết định của HĐNN tại xã.',
            ],
            [
                'title' => 'Quản lý tài chính - ngân sách',
                'description' => 'Quản lý tài chính, ngân sách, tài sản công và đảm bảo sử dụng hiệu quả các nguồn lực của xã.',
            ],
            [
                'title' => 'Tham mưu phát triển kinh tế - xã hội',
                'description' => 'Tham mưu, đề xuất các chính sách, kế hoạch phát triển kinh tế - xã hội phù hợp với tình hình thực tế.',
            ],
            [
                'title' => 'Quản lý an ninh, trật tự',
                'description' => 'Tổ chức thực hiện công tác an ninh, trật tự, phòng chống tội phạm và bảo vệ an toàn cho nhân dân.',
            ],
            [
                'title' => 'Phối hợp thực hiện các chương trình phát triển',
                'description' => 'Phối hợp với các cơ quan, tổ chức trong thực hiện các chương trình phát triển, dự án đầu tư tại xã.',
            ],
            [
                'title' => 'Tiếp nhận và xử lý kiến nghị, khiếu nại',
                'description' => 'Tiếp nhận, xem xét và xử lý các kiến nghị, khiếu nại của nhân dân theo quy định của pháp luật.',
            ],
        ],
        'activities' => [
            [
                'title' => 'Họp UBND định kỳ',
                'description' => 'Tổ chức các cuộc họp UBND định kỳ để thảo luận, quyết định các vấn đề quản lý hành chính.',
            ],
            [
                'title' => 'Triển khai các chương trình phát triển',
                'description' => 'Tổ chức triển khai các chương trình phát triển kinh tế - xã hội, dự án đầu tư tại xã.',
            ],
            [
                'title' => 'Quản lý tài chính - ngân sách',
                'description' => 'Quản lý, sử dụng hiệu quả tài chính, ngân sách và tài sản công của xã.',
            ],
            [
                'title' => 'Tiếp xúc nhân dân',
                'description' => 'Tổ chức tiếp xúc nhân dân, lắng nghe ý kiến, kiến nghị và giải quyết các vấn đề liên quan đến lợi ích của người dân.',
            ],
        ],
        'staff_members' => [
            ['name' => 'Chủ tịch UBND', 'role' => 'Chủ tịch Ủy ban Nhân dân', 'phone' => 'Đang cập nhật'],
            ['name' => 'Phó Chủ tịch UBND 1', 'role' => 'Phó Chủ tịch Ủy ban Nhân dân', 'phone' => 'Đang cập nhật'],
            ['name' => 'Phó Chủ tịch UBND 2', 'role' => 'Phó Chủ tịch Ủy ban Nhân dân', 'phone' => 'Đang cập nhật'],
            ['name' => 'Thư ký UBND', 'role' => 'Thư ký Ủy ban Nhân dân', 'phone' => 'Đang cập nhật'],
            ['name' => 'Trưởng phòng VH-XH', 'role' => 'Trưởng phòng Văn hóa - Xã hội', 'phone' => '0343.791.397'],
            ['name' => 'Trưởng phòng KT', 'role' => 'Trưởng phòng Kinh tế', 'phone' => '0944.942.121'],
            ['name' => 'Trưởng bộ phận HC công', 'role' => 'Trưởng bộ phận Hành chính công', 'phone' => 'Đang cập nhật'],
            ['name' => 'Cán bộ thống kê', 'role' => 'Cán bộ thống kê - Kế hoạch', 'phone' => 'Đang cập nhật'],
        ],
        'highlight_stats' => [
            ['value' => '08', 'label' => 'Nhân sự'],
            ['value' => '06', 'label' => 'Nhóm chức năng'],
            ['value' => '04', 'label' => 'Mảng hoạt động trọng tâm'],
            ['value' => '5/7', 'label' => 'Ngày trực tiếp phục vụ người dân'],
        ],
    ],
];
